сi: refactor cache life sycle time check job v4

diff --git a/.github/workflows/perf-security-monitoring.yml b/.github/workflows/perf-security-monitoring.yml
--- a/.github/workflows/perf-security-monitoring.yml
+++ b/.github/workflows/perf-security-monitoring.yml
@@ -129,77 +129,50 @@ jobs:
         run: lhci autorun --config .lighthouserc.desktop.js
 
   validate-cache-headers:
-      runs-on: ubuntu-24.04
-      timeout-minutes: 2
-      steps:
-        - name: Fetch and validate cache headers of CDN media resources
-          run: |
-            echo "Fetching main page..."
-            curl -s https://chelzoo.ru > page.html
+    runs-on: ubuntu-24.04
+    timeout-minutes: 2
+    steps:
+      - name: Fetch and validate cache headers of CDN media resources
+        run: |
+          echo "Fetching main page..."
+          curl -s https://chelzoo.ru > page.html
 
-            echo "Extracting CDN media resources from HTML..."
-            grep -Eo 'https://cdn\.chelzoo\.ru/[^\"\, ]+\.(svg|jpeg|jpg|png|gif|webp)' page.html | sort -u > urls.txt
+          echo "Extracting CDN media resources from HTML..."
+          grep -Eo 'https://cdn\.chelzoo\.ru/[^\"\, ]+\.(svg|jpeg|jpg|png|gif|webp)|https://chelzoo\.ru/_next/image\?url=[^\"\, ]+' page.html \
+            | sort -u > urls.txt
 
-            echo "Validating Cache-Control headers..."
-            EXITCODE=0
+          echo "Validating Cache-Control headers..."
+          EXITCODE=0
 
-            while IFS= read -r url; do
-              echo "Checking $url"
-              HEADER=$(curl -s -I "$url" | grep -i '^Cache-Control:' | tr -d '\r')
+          while IFS= read -r url; do
+            echo "Checking $url"
+            HEADER=$(curl -s -I "$url" | grep -i '^Cache-Control:' | tr -d '\r')
 
-              if [[ "$url" == *"/_next/static/media/"* ]]; then
-                EXPECTED="max-age=31536000"
-              else
-                EXPECTED="max-age=3600"
-              fi
-
-              if echo "$HEADER" | grep -iq "$EXPECTED"; then
-                echo "✅PASSED: $url"
-              else
-                echo "❌FAILED: $url"
-                echo "   Found:    $HEADER"
-                echo "   Expected to contain: $EXPECTED"
-                EXITCODE=1
-              fi
-            done < urls.txt
-
-            if [[ $EXITCODE -ne 0 ]]; then
-              echo "Some resources have incorrect cache headers."
-              exit 1
+            if [[ "$url" == *"/_next/static/media/"* ]]; then
+              EXPECTED="max-age=31536000"
+            elif [[ "$url" == *"image?url=https%3A%2F%2Fcdn.chelzoo.ru%2F_next%2Fstatic%2Fmedia"* ]]; then
+              EXPECTED="max-age=31536000"
+            elif [[ "$url" == *"image?url=https%3A%2F%2Fstorage.yandexcloud.net"* ]]; then
+              EXPECTED="max-age=3600"
             else
-              echo "All resources have correct cache headers."
+              EXPECTED="max-age=3600"
             fi
 
-  # notify:
-  #   runs-on: ubuntu-24.04
-  #   needs: [validate-robots, jmeter-tests, lighthouse, validate-cache-headers]
-  #   if: always()
-  #   steps:
-  #     - name: Notify on failure
-  #       run: |
-  #         FAIL_MSG=""
+            if echo "$HEADER" | grep -iq "$EXPECTED"; then
+              echo "✅PASSED: $url"
+            else
+              echo "❌FAILED: $url"
+              echo "   Found:    $HEADER"
+              echo "   Expected to contain: $EXPECTED"
+              EXITCODE=1
+            fi
+          done < urls.txt
 
-  #         if [ "${{ needs.validate-robots.result }}" != "success" ]; then
-  #           FAIL_MSG+="\n❌ Robots.txt not matches the right version. Check the pipeline and go to https://chelzoo.ru/robots.txt/"
-  #         fi
-
-  #         if [ "${{ needs.jmeter-tests.result }}" != "success" ]; then
-  #           FAIL_MSG+="\n📉 JMeter tests are failed. Check the pipeline!"
-  #         fi
-
-  #         if [ "${{ needs.lighthouse.result }}" != "success" ]; then
-  #           FAIL_MSG+="\n💡 Lighthouse CI found problems with chelzoo.ru performance or accessibility. Check the pipeline!"
-  #         fi
-
-  #         if [ "${{ needs.validate-cache-headers.result }}" != "success" ]; then
-  #           FAIL_MSG+="\n🧩 There is a problem with Cache-control!"
-  #         fi
+          if [[ $EXITCODE -ne 0 ]]; then
+            echo "Some resources have incorrect cache headers."
+            exit 1
+          else
+            echo "All resources have correct cache headers."
+          fi
 
 
-  #         if [ -n "$FAIL_MSG" ]; then
-  #           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
-  #             -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
-  #             -d text="🚨 CI pipeline has failed with the following errors:$FAIL_MSG\n\n🔗 Подробнее: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-  #         else
-  #           echo "✅ All checks were passed successfully."
-  #         fi
